// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefreshBlazorMemory.Data;

#nullable disable

namespace RefreshBlazorMemory.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefreshBlazorMemory.Models.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Musics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumTitle = "Pepe",
                            Artist = "Mic Pepper",
                            Description = "Dope nok",
                            ReleaseYear = 1999
                        },
                        new
                        {
                            Id = 2,
                            AlbumTitle = "MoreDance",
                            Artist = "Jens Musikmand",
                            Description = "Vildt Nok",
                            ReleaseYear = 2000
                        },
                        new
                        {
                            Id = 3,
                            AlbumTitle = "SuperDanse",
                            Artist = "Danse Mus",
                            Description = "Jeg er træt",
                            ReleaseYear = 2001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
